/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include <app_preference.h>
#include "../particle/garadget.h"
#include <Ecore.h>

typedef struct _uib_main_control_context {
 /* add your variables here */

} uib_main_control_context;

bool isOpen = false;
char *token = NULL;
char *currentDoorName = NULL;
Ecore_Timer *timer = NULL;
Ecore_Timer *animationTimer = NULL;
bool isOpening = false;
int currentFrame = 1;

void setDebugResult(uib_main_view_context *vc, REMOTE_RESULT result) {
	if (result != REMOTE_RESULT_OK) {
		char strval[256];
		sprintf(strval, "%d", result);
		elm_object_text_set(vc->doorName, strval);
	}
	else {
		elm_object_text_set(vc->doorName, currentDoorName);
	}
}

void setImageFrame(uib_main_view_context *vc, int frame) {
	char fileName[256];

	sprintf(&fileName, "%sdoor-%02d.png", app_get_resource_path(), frame);
	elm_image_file_set(vc->DoorImage, fileName, NULL);
}

void updateUi(uib_main_view_context *vc) {
	if (!isOpen) {
		setImageFrame(vc, 1);
		evas_object_show(vc->DoorImage);
		evas_object_hide(vc->NoConfig);
	} else {
		setImageFrame(vc, 15);
		evas_object_show(vc->DoorImage);
		evas_object_hide(vc->NoConfig);
	}
}

void updateState(uib_main_view_context *vc) {
	setDebugResult(vc, getDoorStatus(token, currentDoorName, &isOpen));
	updateUi(vc);
}

Eina_Bool updateStateTimer(void *data) {
	uib_main_view_context *vc = (uib_main_view_context *)data;
	updateState(vc);

	return ECORE_CALLBACK_RENEW;
}

Eina_Bool updateAnimationTimer(void *data) {
	uib_main_view_context *vc = (uib_main_view_context *)data;
	Eina_Bool returnVal = ECORE_CALLBACK_RENEW;

	if (isOpening) {
		currentFrame +=1;

		if (currentFrame == 15) {
			returnVal = ECORE_CALLBACK_CANCEL;
		}
	} else {
		currentFrame -=1;

		if (currentFrame == 1) {
			returnVal = ECORE_CALLBACK_CANCEL;
		}
	}

	setImageFrame(vc, currentFrame);
	return returnVal;
}

void main_onuib_view_create(uib_main_view_context *vc, Evas_Object *obj, void *event_info) {
	char *user;
	char *password;

	bool existing = false;

	// TODO: Cache token in prefs
	preference_is_existing ("token", &existing);
	if (existing && !token) {
		preference_get_string("token", &token);
	}

	preference_is_existing ("user", &existing);
	if (existing) {
		preference_get_string("user", &user);

		preference_is_existing ("password", &existing);
		if (existing) {
			preference_get_string("password", &password);
		}
	}

	if (existing) {
		if (!token) {
			setDebugResult(vc, getToken(&token, user, password));
			preference_set_string("token", token);
		}

		if (!currentDoorName) {
			setDebugResult(vc, getDoors(token, 0, &currentDoorName));
		}

		updateState(vc);
		timer = ecore_timer_add(60, updateStateTimer, (void*)vc);
	}
}

void main_DoorOpenImage_onclicked(uib_main_view_context *vc, Evas_Object *obj, void *event_info) {
	setDebugResult(vc, getDoorStatus(token, currentDoorName, &isOpen));
	if (isOpen) {
		setDebugResult(vc, openDoor(token, currentDoorName, "close"));
		isOpening = false;
		currentFrame = 15;
	}
	else {
		setDebugResult(vc, openDoor(token, currentDoorName, "open"));
		isOpening = true;
		currentFrame = 1;
	}

	animationTimer = ecore_timer_add(1, updateAnimationTimer, (void*)vc);
}


void main_bntConfig_onclicked(uib_main_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function main_connection_main_bntConfig_onclicked
	if (timer) {
		ecore_timer_del(timer);
	}

	if (animationTimer) {
		ecore_timer_del(animationTimer);
	}
}

void main_bntConfig_onclicked_post(void* param, uib_main_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function main_connection_main_bntConfig_onclicked
}
