/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include <app_preference.h>
#include <inputmethod.h>

typedef struct _uib_viewConfig_control_context {
 /* add your variables here */

} uib_viewConfig_control_context;


void viewConfig_OK_onclicked(uib_viewConfig_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function viewConfig_connection_viewConfig_OK_onclicked
	preference_set_string("user", elm_object_text_get(vc->Username));
	preference_set_string("password", elm_object_text_get(vc->Password));

}

void viewConfig_OK_onclicked_post(void* param, uib_viewConfig_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function viewConfig_connection_viewConfig_OK_onclicked

}

void viewConfig_onuib_view_create(uib_viewConfig_view_context *vc, Evas_Object *obj, void *event_info) {
	elm_entry_input_panel_layout_set(vc->Username, ELM_INPUT_PANEL_LAYOUT_EMAIL);
	elm_entry_input_hint_set(vc->Username, false);
	elm_entry_input_panel_return_key_type_set(vc->Username, ELM_INPUT_PANEL_RETURN_KEY_TYPE_DONE);

	char *user;
	char *password;

	bool existing = false;

	preference_is_existing ("user", &existing);

	if (existing) {
		preference_get_string("user", &user);
		elm_object_text_set(vc->Username, user);
	}

	preference_is_existing ("password", &existing);
	if (existing) {
		preference_get_string("password", &password);
		elm_object_text_set(vc->Password, password);
	}
}

void viewConfig_Username_onclicked(uib_viewConfig_view_context *vc, Evas_Object *obj, void *event_info) {
	evas_object_hide(vc->User);
	evas_object_hide(vc->Pass);
	evas_object_hide(vc->Password);
	evas_object_hide(vc->OK);
}

void viewConfig_image3_onclicked(uib_viewConfig_view_context *vc, Evas_Object *obj, void *event_info) {
	evas_object_show(vc->User);
	evas_object_show(vc->Username);
	evas_object_show(vc->Pass);
	evas_object_show(vc->Password);
	evas_object_show(vc->OK);

	elm_entry_input_panel_hide(vc->Username);
	elm_entry_input_panel_hide(vc->Password);
}

void viewConfig_Password_onclicked(uib_viewConfig_view_context *vc, Evas_Object *obj, void *event_info) {
	evas_object_hide(vc->User);
	evas_object_hide(vc->Username);
	evas_object_hide(vc->Pass);
	evas_object_hide(vc->OK);
}


void viewConfig_Username_onactivated(uib_viewConfig_view_context *vc, Evas_Object *obj, void *event_info) {
	evas_object_show(vc->User);
	evas_object_show(vc->Username);
	evas_object_show(vc->Pass);
	evas_object_show(vc->Password);
	evas_object_show(vc->OK);

	elm_entry_input_panel_hide(vc->Username);
	elm_entry_input_panel_hide(vc->Password);
}

void viewConfig_Password_onactivated(uib_viewConfig_view_context *vc, Evas_Object *obj, void *event_info) {
	evas_object_show(vc->User);
	evas_object_show(vc->Username);
	evas_object_show(vc->Pass);
	evas_object_show(vc->Password);
	evas_object_show(vc->OK);

	elm_entry_input_panel_hide(vc->Username);
	elm_entry_input_panel_hide(vc->Password);
}

