
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void viewConfig_onuib_view_create(uib_viewConfig_view_context*, Evas_Object*, void*);
void viewConfig_image3_onclicked(uib_viewConfig_view_context*, Evas_Object*, void*);
void connection_viewConfig_OK_onclicked(uib_viewConfig_view_context*, Evas_Object*, void*);
void viewConfig_Username_onclicked(uib_viewConfig_view_context*, Evas_Object*, void*);
void viewConfig_Username_onactivated(uib_viewConfig_view_context*, Evas_Object*, void*);
void viewConfig_Password_onclicked(uib_viewConfig_view_context*, Evas_Object*, void*);
void viewConfig_Password_onactivated(uib_viewConfig_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_viewConfig_create(Evas_Object* parent, void* create_callback_param) {
	uib_viewConfig_view_context* vc = calloc(1, sizeof(uib_viewConfig_view_context));
	vc->parent = parent;
	vc->view_name = "viewConfig";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid2) {
		vc->grid2= elm_grid_add(parent);
		vc->root_container = vc->grid2;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->root_container, "uib,view,create", (Evas_Smart_Cb)viewConfig_onuib_view_create, vc);
	evas_object_smart_callback_add(vc->image3, "clicked", (Evas_Smart_Cb)viewConfig_image3_onclicked, vc);
	evas_object_smart_callback_add(vc->OK, "clicked", (Evas_Smart_Cb)connection_viewConfig_OK_onclicked, vc);

	evas_object_smart_callback_add(vc->Username, "clicked", (Evas_Smart_Cb)viewConfig_Username_onclicked, vc);
	evas_object_smart_callback_add(vc->Username, "activated", (Evas_Smart_Cb)viewConfig_Username_onactivated, vc);
	evas_object_smart_callback_add(vc->Password, "clicked", (Evas_Smart_Cb)viewConfig_Password_onclicked, vc);
	evas_object_smart_callback_add(vc->Password, "activated", (Evas_Smart_Cb)viewConfig_Password_onactivated, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_viewConfig_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_viewConfig_view_context* vc = (uib_viewConfig_view_context*)uib_app_manager->find_view_context("viewConfig");
	if(!vc) {
		return;
	}
	if(vc->grid2) {
		elm_grid_clear(vc->grid2, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid2, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid2, 1.0, 1.0);		elm_grid_size_set(vc->grid2, 1000, 1000);
		if (!vc->image3) {
			vc->image3 = elm_image_add(vc->grid2);
		}
		if(vc->image3) {
			elm_image_smooth_set(vc->image3, EINA_TRUE);
			elm_image_no_scale_set(vc->image3, EINA_FALSE);
			elm_image_resizable_set(vc->image3, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->image3, EINA_FALSE);
			elm_image_fill_outside_set(vc->image3, EINA_FALSE);
			elm_image_editable_set(vc->image3, EINA_FALSE);
			evas_object_size_hint_align_set(vc->image3, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->image3, 1.0, 1.0);
			evas_object_show(vc->image3);
		}
		if (!vc->OK) {
			vc->OK = elm_button_add(vc->grid2);
		}
		if (vc->OK) {
			evas_object_size_hint_align_set(vc->OK, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->OK, 1.0, 1.0);			elm_object_text_set(vc->OK,_UIB_LOCALE("OK"));
			elm_object_style_set(vc->OK,"bottom");
			evas_object_show(vc->OK);
		}
		if (!vc->Username) {
			vc->Username= elm_entry_add(vc->grid2);
		}
		if(vc->Username) {
			elm_object_text_set(vc->Username,_UIB_LOCALE("user@domain.com"));
			elm_entry_single_line_set(vc->Username, EINA_TRUE);
			elm_entry_password_set(vc->Username, EINA_FALSE);
			elm_entry_editable_set(vc->Username, EINA_TRUE);
			elm_entry_scrollable_set(vc->Username, EINA_FALSE);
			evas_object_size_hint_align_set(vc->Username, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->Username, 1.0, 1.0);
			elm_object_disabled_set(vc->Username, EINA_FALSE);
			evas_object_show(vc->Username);
		}
		if (!vc->Password) {
			vc->Password= elm_entry_add(vc->grid2);
		}
		if(vc->Password) {
			elm_object_text_set(vc->Password,_UIB_LOCALE("password"));
			elm_entry_single_line_set(vc->Password, EINA_FALSE);
			elm_entry_password_set(vc->Password, EINA_TRUE);
			elm_entry_editable_set(vc->Password, EINA_TRUE);
			elm_entry_scrollable_set(vc->Password, EINA_FALSE);
			evas_object_size_hint_align_set(vc->Password, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->Password, 1.0, 1.0);
			elm_object_disabled_set(vc->Password, EINA_FALSE);
			evas_object_show(vc->Password);
		}
		if (!vc->User) {
			vc->User= elm_entry_add(vc->grid2);
		}
		if(vc->User) {
			elm_object_text_set(vc->User,_UIB_LOCALE("User:"));
			elm_entry_single_line_set(vc->User, EINA_FALSE);
			elm_entry_password_set(vc->User, EINA_FALSE);
			elm_entry_editable_set(vc->User, EINA_FALSE);
			elm_entry_scrollable_set(vc->User, EINA_FALSE);
			evas_object_size_hint_align_set(vc->User, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->User, 1.0, 1.0);
			elm_object_disabled_set(vc->User, EINA_FALSE);
			evas_object_show(vc->User);
		}
		if (!vc->Pass) {
			vc->Pass= elm_entry_add(vc->grid2);
		}
		if(vc->Pass) {
			elm_object_text_set(vc->Pass,_UIB_LOCALE("Password"));
			elm_entry_single_line_set(vc->Pass, EINA_FALSE);
			elm_entry_password_set(vc->Pass, EINA_FALSE);
			elm_entry_editable_set(vc->Pass, EINA_FALSE);
			elm_entry_scrollable_set(vc->Pass, EINA_FALSE);
			evas_object_size_hint_align_set(vc->Pass, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->Pass, 1.0, 1.0);
			elm_object_disabled_set(vc->Pass, EINA_FALSE);
			evas_object_show(vc->Pass);
		}
		elm_grid_pack(vc->grid2, vc->image3, 11, -3, 1000, 1025);		elm_grid_pack(vc->grid2, vc->OK, 316, 704, 364, 364);		elm_grid_pack(vc->grid2, vc->Username, 185, 217, 758, 139);		elm_grid_pack(vc->grid2, vc->Password, 193, 477, 653, 139);		elm_grid_pack(vc->grid2, vc->User, 177, 125, 417, 139);		elm_grid_pack(vc->grid2, vc->Pass, 184, 383, 417, 139);		evas_object_show(vc->grid2);
	}
}

