
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void main_onuib_view_create(uib_main_view_context*, Evas_Object*, void*);
void connection_main_bntConfig_onclicked(uib_main_view_context*, Evas_Object*, void*);
void main_image1_onclicked(uib_main_view_context*, Evas_Object*, void*);
void main_DoorOpenImage_onclicked(uib_main_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_main_create(Evas_Object* parent, void* create_callback_param) {
	uib_main_view_context* vc = calloc(1, sizeof(uib_main_view_context));
	vc->parent = parent;
	vc->view_name = "main";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->root_container, "uib,view,create", (Evas_Smart_Cb)main_onuib_view_create, vc);
	evas_object_smart_callback_add(vc->bntConfig, "clicked", (Evas_Smart_Cb)connection_main_bntConfig_onclicked, vc);

	evas_object_smart_callback_add(vc->DoorClosedImage, "clicked", (Evas_Smart_Cb)main_image1_onclicked, vc);
	evas_object_smart_callback_add(vc->DoorOpenImage, "clicked", (Evas_Smart_Cb)main_DoorOpenImage_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_main_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_main_view_context* vc = (uib_main_view_context*)uib_app_manager->find_view_context("main");
	if(!vc) {
		return;
	}
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->bntConfig) {
			vc->bntConfig = elm_button_add(vc->grid1);
		}
		if (vc->bntConfig) {
			evas_object_size_hint_align_set(vc->bntConfig, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->bntConfig, 1.0, 1.0);			elm_object_text_set(vc->bntConfig,_UIB_LOCALE("Config"));
			elm_object_style_set(vc->bntConfig,"bottom");
			evas_object_show(vc->bntConfig);
		}
		if (!vc->DoorClosedImage) {
			vc->DoorClosedImage = elm_image_add(vc->grid1);
		}
		if(vc->DoorClosedImage) {
			char *resource_path = NULL;
			uib_util_rm_get_resource_path(APP_RESOURCE_TYPE_IMAGE, "door-01.png", &resource_path);
			elm_image_file_set(vc->DoorClosedImage, resource_path, NULL);
			if(resource_path) {
				free(resource_path);
			}
			elm_image_smooth_set(vc->DoorClosedImage, EINA_TRUE);
			elm_image_no_scale_set(vc->DoorClosedImage, EINA_FALSE);
			elm_image_resizable_set(vc->DoorClosedImage, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->DoorClosedImage, EINA_FALSE);
			elm_image_fill_outside_set(vc->DoorClosedImage, EINA_FALSE);
			elm_image_editable_set(vc->DoorClosedImage, EINA_FALSE);
			evas_object_size_hint_align_set(vc->DoorClosedImage, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->DoorClosedImage, 1.0, 1.0);
			evas_object_hide(vc->DoorClosedImage);
		}
		if (!vc->NoConfig) {
			vc->NoConfig= elm_entry_add(vc->grid1);
		}
		if(vc->NoConfig) {
			elm_object_text_set(vc->NoConfig,_UIB_LOCALE("No Configuration Found. Please Configure."));
			elm_entry_single_line_set(vc->NoConfig, EINA_FALSE);
			elm_entry_password_set(vc->NoConfig, EINA_FALSE);
			elm_entry_editable_set(vc->NoConfig, EINA_FALSE);
			elm_entry_scrollable_set(vc->NoConfig, EINA_FALSE);
			evas_object_size_hint_align_set(vc->NoConfig, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->NoConfig, 1.0, 1.0);
			elm_object_disabled_set(vc->NoConfig, EINA_FALSE);
			evas_object_show(vc->NoConfig);
		}
		if (!vc->DoorOpenImage) {
			vc->DoorOpenImage = elm_image_add(vc->grid1);
		}
		if(vc->DoorOpenImage) {
			char *resource_path = NULL;
			uib_util_rm_get_resource_path(APP_RESOURCE_TYPE_IMAGE, "door-15.png", &resource_path);
			elm_image_file_set(vc->DoorOpenImage, resource_path, NULL);
			if(resource_path) {
				free(resource_path);
			}
			elm_image_smooth_set(vc->DoorOpenImage, EINA_TRUE);
			elm_image_no_scale_set(vc->DoorOpenImage, EINA_FALSE);
			elm_image_resizable_set(vc->DoorOpenImage, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->DoorOpenImage, EINA_FALSE);
			elm_image_fill_outside_set(vc->DoorOpenImage, EINA_FALSE);
			elm_image_editable_set(vc->DoorOpenImage, EINA_FALSE);
			evas_object_size_hint_align_set(vc->DoorOpenImage, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->DoorOpenImage, 1.0, 1.0);
			evas_object_hide(vc->DoorOpenImage);
		}
		elm_grid_pack(vc->grid1, vc->bntConfig, 322, 694, 364, 364);		elm_grid_pack(vc->grid1, vc->DoorClosedImage, 269, 133, 501, 509);		elm_grid_pack(vc->grid1, vc->NoConfig, 169, 273, 716, 281);		elm_grid_pack(vc->grid1, vc->DoorOpenImage, 272, 136, 503, 511);		evas_object_show(vc->grid1);
	}
}

